security:
  encoders:
    BalticRobo\Api\Entity\User\User:
      algorithm: argon2i
  providers:
    user:
      id: BalticRobo\Api\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)/
      security: false
    doc:
      pattern: ^/doc$
      security: false
    jwt:
      pattern: ^/security/
      anonymous: ~
      stateless: true
      json_login:
        check_path: balticrobo_api_security_createtoken
        username_path: email
        password_path: password
        remember_me: false
      logout: ~
      guard:
        provider: user
        authenticator: BalticRobo\Api\Security\CredentialsAuthenticator
    main:
      pattern: ^/
      anonymous: false
      stateless: true
      guard:
        authenticator: BalticRobo\Api\Security\TokenAuthenticator
