version: '3.5'

services:
  php:
    build: ./.misc/docker/php
    volumes:
    - .:/var/www/app
    working_dir: /var/www/app
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    - ./.misc/docker/db/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  www:
    image: nginx:1.15
    volumes:
    - ./public:/var/www/app/public
    - ./.misc/docker/www:/etc/nginx/conf.d
    ports:
    - 8000:80
    working_dir: /var/www/app/public
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
    - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
    - 8010:80
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      API_URL: http://localhost:8000/doc
    ports:
    - 8011:8080

volumes:
  db_data:
